name: Create production promotion pull request
on:
  pull_request:
    branches:
      - main
jobs:
  productionPromotion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: production
      - name: Reset promotion branch
        run: |
          git fetch origin main:main
          git reset --hard main
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          branch: production-promotion
  new-step:
    runs-on: ubuntu-latest
    steps:
      - name: Echo test confidential secrets
        run: echo '${{ secrets.CONFIDENTIAL_TOKEN }}''