on: 
  pull_request_target:
    branches: main

jobs:
  create_comment:
    runs-on: ubuntu-latest
    name: Create a comment
    steps:
      - name: Comment current pull request
        uses: alawiii521/current-pr-comment@v1.0
        with:
          comment: "Hello world!"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
